base:
  project: winequality-project
  random_state: 42
  target_col: TARGET

data_source:
  s3_source: data_given/winequality.csv

load_data:
  raw_dataset_csv: data/raw/winequality.csv

split_data:
  train_data_path: data/processed/train_data.csv
  test_data_path: data/processed/test_data.csv
  test_size: 0.2